### ISSUE TITLE
번역: command-line.md

### ISSUE THREAD

**Issue by GzuPark** [missing-semester-kr/missing-semester-kr.github.io#3]
- [command-line.md](https://github.com/missing-semester-kr/missing-semester-kr.github.io/blob/master/_2020/command-line.md)

**Comment by GzuPark** [comment]
- [진행중](https://github.com/missing-semester-kr/missing-semester-kr.github.io/commit/74ee7970f78ad6cc4b5f12e01344855bdf3ec275)
  - [x] Job control
  - [x] Background and pausing process
  - [x] Terminal multiplexer
  - [x] Alias

**Comment by hasantezcan** [comment]
Did you finish the translation, my friend? @GzuPark
