### ISSUE TITLE
번역: course-shell.md

### ISSUE THREAD

**Issue by GzuPark** [missing-semester-kr/missing-semester-kr.github.io#4]
- [course-shell.md](https://github.com/missing-semester-kr/missing-semester-kr.github.io/blob/master/_2020/course-shell.md)

**Comment by ddaeddae-kim** [comment]
해당 수업은 PR 했습니다!

**Comment by GzuPark** [comment]
@ddaeddae-kim 감사합니다! merge 시켰고, 차후에 번역이 모두 되면 전체적인 용어 통일 등을 할 예정입니다. 🤓
